#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_thoitrangtreem")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchitietdonhang(chitietdonhang instance);
    partial void Updatechitietdonhang(chitietdonhang instance);
    partial void Deletechitietdonhang(chitietdonhang instance);
    partial void Inserttrangthaidonhang(trangthaidonhang instance);
    partial void Updatetrangthaidonhang(trangthaidonhang instance);
    partial void Deletetrangthaidonhang(trangthaidonhang instance);
    partial void Insertdanhgiasanpham(danhgiasanpham instance);
    partial void Updatedanhgiasanpham(danhgiasanpham instance);
    partial void Deletedanhgiasanpham(danhgiasanpham instance);
    partial void Insertdanhmuc(danhmuc instance);
    partial void Updatedanhmuc(danhmuc instance);
    partial void Deletedanhmuc(danhmuc instance);
    partial void Insertdiachi(diachi instance);
    partial void Updatediachi(diachi instance);
    partial void Deletediachi(diachi instance);
    partial void InsertDM_ManHinh(DM_ManHinh instance);
    partial void UpdateDM_ManHinh(DM_ManHinh instance);
    partial void DeleteDM_ManHinh(DM_ManHinh instance);
    partial void Insertdonhang(donhang instance);
    partial void Updatedonhang(donhang instance);
    partial void Deletedonhang(donhang instance);
    partial void Insertgiohang(giohang instance);
    partial void Updategiohang(giohang instance);
    partial void Deletegiohang(giohang instance);
    partial void Insertkichcosanpham(kichcosanpham instance);
    partial void Updatekichcosanpham(kichcosanpham instance);
    partial void Deletekichcosanpham(kichcosanpham instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertkhuyenmai(khuyenmai instance);
    partial void Updatekhuyenmai(khuyenmai instance);
    partial void Deletekhuyenmai(khuyenmai instance);
    partial void Insertloaisanpham(loaisanpham instance);
    partial void Updateloaisanpham(loaisanpham instance);
    partial void Deleteloaisanpham(loaisanpham instance);
    partial void InsertQL_NguoiDung(QL_NguoiDung instance);
    partial void UpdateQL_NguoiDung(QL_NguoiDung instance);
    partial void DeleteQL_NguoiDung(QL_NguoiDung instance);
    partial void InsertQL_NguoiDungNhomNguoiDung(QL_NguoiDungNhomNguoiDung instance);
    partial void UpdateQL_NguoiDungNhomNguoiDung(QL_NguoiDungNhomNguoiDung instance);
    partial void DeleteQL_NguoiDungNhomNguoiDung(QL_NguoiDungNhomNguoiDung instance);
    partial void InsertQL_NhomNguoiDung(QL_NhomNguoiDung instance);
    partial void UpdateQL_NhomNguoiDung(QL_NhomNguoiDung instance);
    partial void DeleteQL_NhomNguoiDung(QL_NhomNguoiDung instance);
    partial void InsertQL_PhanQuyen(QL_PhanQuyen instance);
    partial void UpdateQL_PhanQuyen(QL_PhanQuyen instance);
    partial void DeleteQL_PhanQuyen(QL_PhanQuyen instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    #endregion
		
		public DBDataContext() : 
				base(global::DAL.Properties.Settings.Default.db_thoitrangtreemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this.GetTable<chitietdonhang>();
			}
		}
		
		public System.Data.Linq.Table<trangthaidonhang> trangthaidonhangs
		{
			get
			{
				return this.GetTable<trangthaidonhang>();
			}
		}
		
		public System.Data.Linq.Table<danhgiasanpham> danhgiasanphams
		{
			get
			{
				return this.GetTable<danhgiasanpham>();
			}
		}
		
		public System.Data.Linq.Table<danhmuc> danhmucs
		{
			get
			{
				return this.GetTable<danhmuc>();
			}
		}
		
		public System.Data.Linq.Table<diachi> diachis
		{
			get
			{
				return this.GetTable<diachi>();
			}
		}
		
		public System.Data.Linq.Table<DM_ManHinh> DM_ManHinhs
		{
			get
			{
				return this.GetTable<DM_ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<donhang> donhangs
		{
			get
			{
				return this.GetTable<donhang>();
			}
		}
		
		public System.Data.Linq.Table<giohang> giohangs
		{
			get
			{
				return this.GetTable<giohang>();
			}
		}
		
		public System.Data.Linq.Table<kichcosanpham> kichcosanphams
		{
			get
			{
				return this.GetTable<kichcosanpham>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<khuyenmai> khuyenmais
		{
			get
			{
				return this.GetTable<khuyenmai>();
			}
		}
		
		public System.Data.Linq.Table<loaisanpham> loaisanphams
		{
			get
			{
				return this.GetTable<loaisanpham>();
			}
		}
		
		public System.Data.Linq.Table<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this.GetTable<QL_NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_NguoiDungNhomNguoiDung> QL_NguoiDungNhomNguoiDungs
		{
			get
			{
				return this.GetTable<QL_NguoiDungNhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhomNguoiDung> QL_NhomNguoiDungs
		{
			get
			{
				return this.GetTable<QL_NhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_PhanQuyen> QL_PhanQuyens
		{
			get
			{
				return this.GetTable<QL_PhanQuyen>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdonhang")]
	public partial class chitietdonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SanPham_id;
		
		private int _DonHang_id;
		
		private double _gia;
		
		private int _soluong;
		
		private EntityRef<donhang> _donhang;
		
		private EntityRef<kichcosanpham> _kichcosanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSanPham_idChanging(int value);
    partial void OnSanPham_idChanged();
    partial void OnDonHang_idChanging(int value);
    partial void OnDonHang_idChanged();
    partial void OngiaChanging(double value);
    partial void OngiaChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    #endregion
		
		public chitietdonhang()
		{
			this._donhang = default(EntityRef<donhang>);
			this._kichcosanpham = default(EntityRef<kichcosanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPham_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SanPham_id
		{
			get
			{
				return this._SanPham_id;
			}
			set
			{
				if ((this._SanPham_id != value))
				{
					if (this._kichcosanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._SanPham_id = value;
					this.SendPropertyChanged("SanPham_id");
					this.OnSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonHang_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DonHang_id
		{
			get
			{
				return this._DonHang_id;
			}
			set
			{
				if ((this._DonHang_id != value))
				{
					if (this._donhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDonHang_idChanging(value);
					this.SendPropertyChanging();
					this._DonHang_id = value;
					this.SendPropertyChanged("DonHang_id");
					this.OnDonHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float NOT NULL")]
		public double gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donhang_chitietdonhang", Storage="_donhang", ThisKey="DonHang_id", OtherKey="id", IsForeignKey=true)]
		public donhang donhang
		{
			get
			{
				return this._donhang.Entity;
			}
			set
			{
				donhang previousValue = this._donhang.Entity;
				if (((previousValue != value) 
							|| (this._donhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._donhang.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._donhang.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._DonHang_id = value.id;
					}
					else
					{
						this._DonHang_id = default(int);
					}
					this.SendPropertyChanged("donhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichcosanpham_chitietdonhang", Storage="_kichcosanpham", ThisKey="SanPham_id", OtherKey="id", IsForeignKey=true)]
		public kichcosanpham kichcosanpham
		{
			get
			{
				return this._kichcosanpham.Entity;
			}
			set
			{
				kichcosanpham previousValue = this._kichcosanpham.Entity;
				if (((previousValue != value) 
							|| (this._kichcosanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kichcosanpham.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._kichcosanpham.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._SanPham_id = value.id;
					}
					else
					{
						this._SanPham_id = default(int);
					}
					this.SendPropertyChanged("kichcosanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trangthaidonhang")]
	public partial class trangthaidonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _trangthai;
		
		private EntitySet<donhang> _donhangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    #endregion
		
		public trangthaidonhang()
		{
			this._donhangs = new EntitySet<donhang>(new Action<donhang>(this.attach_donhangs), new Action<donhang>(this.detach_donhangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(55) NOT NULL", CanBeNull=false)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trangthaidonhang_donhang", Storage="_donhangs", ThisKey="id", OtherKey="TrangThaiDonHang_id")]
		public EntitySet<donhang> donhangs
		{
			get
			{
				return this._donhangs;
			}
			set
			{
				this._donhangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.trangthaidonhang = this;
		}
		
		private void detach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.trangthaidonhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhgiasanpham")]
	public partial class danhgiasanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHang_id;
		
		private System.Nullable<double> _sosao;
		
		private string _binhluan;
		
		private int _SanPham_id;
		
		private int _DonHang_id;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHang_idChanging(int value);
    partial void OnKhachHang_idChanged();
    partial void OnsosaoChanging(System.Nullable<double> value);
    partial void OnsosaoChanged();
    partial void OnbinhluanChanging(string value);
    partial void OnbinhluanChanged();
    partial void OnSanPham_idChanging(int value);
    partial void OnSanPham_idChanged();
    partial void OnDonHang_idChanging(int value);
    partial void OnDonHang_idChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    #endregion
		
		public danhgiasanpham()
		{
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KhachHang_id
		{
			get
			{
				return this._KhachHang_id;
			}
			set
			{
				if ((this._KhachHang_id != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHang_idChanging(value);
					this.SendPropertyChanging();
					this._KhachHang_id = value;
					this.SendPropertyChanged("KhachHang_id");
					this.OnKhachHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sosao", DbType="Float")]
		public System.Nullable<double> sosao
		{
			get
			{
				return this._sosao;
			}
			set
			{
				if ((this._sosao != value))
				{
					this.OnsosaoChanging(value);
					this.SendPropertyChanging();
					this._sosao = value;
					this.SendPropertyChanged("sosao");
					this.OnsosaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_binhluan", DbType="NVarChar(255)")]
		public string binhluan
		{
			get
			{
				return this._binhluan;
			}
			set
			{
				if ((this._binhluan != value))
				{
					this.OnbinhluanChanging(value);
					this.SendPropertyChanging();
					this._binhluan = value;
					this.SendPropertyChanged("binhluan");
					this.OnbinhluanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPham_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SanPham_id
		{
			get
			{
				return this._SanPham_id;
			}
			set
			{
				if ((this._SanPham_id != value))
				{
					this.OnSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._SanPham_id = value;
					this.SendPropertyChanged("SanPham_id");
					this.OnSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonHang_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DonHang_id
		{
			get
			{
				return this._DonHang_id;
			}
			set
			{
				if ((this._DonHang_id != value))
				{
					this.OnDonHang_idChanging(value);
					this.SendPropertyChanging();
					this._DonHang_id = value;
					this.SendPropertyChanged("DonHang_id");
					this.OnDonHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_danhgiasanpham", Storage="_khachhang", ThisKey="KhachHang_id", OtherKey="id", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.danhgiasanphams.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.danhgiasanphams.Add(this);
						this._KhachHang_id = value.id;
					}
					else
					{
						this._KhachHang_id = default(int);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhmuc")]
	public partial class danhmuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public danhmuc()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_sanphams", ThisKey="id", OtherKey="DanhMuc_id")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.diachi")]
	public partial class diachi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sdt;
		
		private string _diachi1;
		
		private string _diachicuthe;
		
		private System.Nullable<int> _KhachHang_id;
		
		private System.Nullable<bool> _macdinh;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Ondiachi1Changing(string value);
    partial void Ondiachi1Changed();
    partial void OndiachicutheChanging(string value);
    partial void OndiachicutheChanged();
    partial void OnKhachHang_idChanging(System.Nullable<int> value);
    partial void OnKhachHang_idChanged();
    partial void OnmacdinhChanging(System.Nullable<bool> value);
    partial void OnmacdinhChanged();
    #endregion
		
		public diachi()
		{
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="diachi", Storage="_diachi1", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string diachi1
		{
			get
			{
				return this._diachi1;
			}
			set
			{
				if ((this._diachi1 != value))
				{
					this.Ondiachi1Changing(value);
					this.SendPropertyChanging();
					this._diachi1 = value;
					this.SendPropertyChanged("diachi1");
					this.Ondiachi1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachicuthe", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string diachicuthe
		{
			get
			{
				return this._diachicuthe;
			}
			set
			{
				if ((this._diachicuthe != value))
				{
					this.OndiachicutheChanging(value);
					this.SendPropertyChanging();
					this._diachicuthe = value;
					this.SendPropertyChanged("diachicuthe");
					this.OndiachicutheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang_id", DbType="Int")]
		public System.Nullable<int> KhachHang_id
		{
			get
			{
				return this._KhachHang_id;
			}
			set
			{
				if ((this._KhachHang_id != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHang_idChanging(value);
					this.SendPropertyChanging();
					this._KhachHang_id = value;
					this.SendPropertyChanged("KhachHang_id");
					this.OnKhachHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macdinh", DbType="Bit")]
		public System.Nullable<bool> macdinh
		{
			get
			{
				return this._macdinh;
			}
			set
			{
				if ((this._macdinh != value))
				{
					this.OnmacdinhChanging(value);
					this.SendPropertyChanging();
					this._macdinh = value;
					this.SendPropertyChanged("macdinh");
					this.OnmacdinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_diachi", Storage="_khachhang", ThisKey="KhachHang_id", OtherKey="id", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.diachis.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.diachis.Add(this);
						this._KhachHang_id = value.id;
					}
					else
					{
						this._KhachHang_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_ManHinh")]
	public partial class DM_ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaManHinh;
		
		private string _TenManHinh;
		
		private EntitySet<QL_PhanQuyen> _QL_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    #endregion
		
		public DM_ManHinh()
		{
			this._QL_PhanQuyens = new EntitySet<QL_PhanQuyen>(new Action<QL_PhanQuyen>(this.attach_QL_PhanQuyens), new Action<QL_PhanQuyen>(this.detach_QL_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_ManHinh_QL_PhanQuyen", Storage="_QL_PhanQuyens", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<QL_PhanQuyen> QL_PhanQuyens
		{
			get
			{
				return this._QL_PhanQuyens;
			}
			set
			{
				this._QL_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_PhanQuyens(QL_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.DM_ManHinh = this;
		}
		
		private void detach_QL_PhanQuyens(QL_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.DM_ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.donhang")]
	public partial class donhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private double _tongtien;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private System.Nullable<System.DateTime> _ngaysua;
		
		private System.Nullable<int> _TrangThaiDonHang_id;
		
		private System.Nullable<int> _KhachHang_id;
		
		private string _diachi;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntityRef<trangthaidonhang> _trangthaidonhang;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntongtienChanging(double value);
    partial void OntongtienChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    partial void OnngaysuaChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysuaChanged();
    partial void OnTrangThaiDonHang_idChanging(System.Nullable<int> value);
    partial void OnTrangThaiDonHang_idChanged();
    partial void OnKhachHang_idChanging(System.Nullable<int> value);
    partial void OnKhachHang_idChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public donhang()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._trangthaidonhang = default(EntityRef<trangthaidonhang>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float NOT NULL")]
		public double tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysua", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysua
		{
			get
			{
				return this._ngaysua;
			}
			set
			{
				if ((this._ngaysua != value))
				{
					this.OnngaysuaChanging(value);
					this.SendPropertyChanging();
					this._ngaysua = value;
					this.SendPropertyChanged("ngaysua");
					this.OnngaysuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonHang_id", DbType="Int")]
		public System.Nullable<int> TrangThaiDonHang_id
		{
			get
			{
				return this._TrangThaiDonHang_id;
			}
			set
			{
				if ((this._TrangThaiDonHang_id != value))
				{
					if (this._trangthaidonhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTrangThaiDonHang_idChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDonHang_id = value;
					this.SendPropertyChanged("TrangThaiDonHang_id");
					this.OnTrangThaiDonHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang_id", DbType="Int")]
		public System.Nullable<int> KhachHang_id
		{
			get
			{
				return this._KhachHang_id;
			}
			set
			{
				if ((this._KhachHang_id != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHang_idChanging(value);
					this.SendPropertyChanging();
					this._KhachHang_id = value;
					this.SendPropertyChanged("KhachHang_id");
					this.OnKhachHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donhang_chitietdonhang", Storage="_chitietdonhangs", ThisKey="id", OtherKey="DonHang_id")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="trangthaidonhang_donhang", Storage="_trangthaidonhang", ThisKey="TrangThaiDonHang_id", OtherKey="id", IsForeignKey=true)]
		public trangthaidonhang trangthaidonhang
		{
			get
			{
				return this._trangthaidonhang.Entity;
			}
			set
			{
				trangthaidonhang previousValue = this._trangthaidonhang.Entity;
				if (((previousValue != value) 
							|| (this._trangthaidonhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._trangthaidonhang.Entity = null;
						previousValue.donhangs.Remove(this);
					}
					this._trangthaidonhang.Entity = value;
					if ((value != null))
					{
						value.donhangs.Add(this);
						this._TrangThaiDonHang_id = value.id;
					}
					else
					{
						this._TrangThaiDonHang_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("trangthaidonhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_donhang", Storage="_khachhang", ThisKey="KhachHang_id", OtherKey="id", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.donhangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.donhangs.Add(this);
						this._KhachHang_id = value.id;
					}
					else
					{
						this._KhachHang_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.donhang = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.donhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.giohang")]
	public partial class giohang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KhachHang_id;
		
		private int _KichCoSanPham_id;
		
		private int _soluong;
		
		private System.Nullable<System.DateTime> _ngaythem;
		
		private EntityRef<kichcosanpham> _kichcosanpham;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhachHang_idChanging(int value);
    partial void OnKhachHang_idChanged();
    partial void OnKichCoSanPham_idChanging(int value);
    partial void OnKichCoSanPham_idChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OnngaythemChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythemChanged();
    #endregion
		
		public giohang()
		{
			this._kichcosanpham = default(EntityRef<kichcosanpham>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhachHang_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KhachHang_id
		{
			get
			{
				return this._KhachHang_id;
			}
			set
			{
				if ((this._KhachHang_id != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhachHang_idChanging(value);
					this.SendPropertyChanging();
					this._KhachHang_id = value;
					this.SendPropertyChanged("KhachHang_id");
					this.OnKhachHang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichCoSanPham_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KichCoSanPham_id
		{
			get
			{
				return this._KichCoSanPham_id;
			}
			set
			{
				if ((this._KichCoSanPham_id != value))
				{
					if (this._kichcosanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKichCoSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._KichCoSanPham_id = value;
					this.SendPropertyChanged("KichCoSanPham_id");
					this.OnKichCoSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythem", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaythem
		{
			get
			{
				return this._ngaythem;
			}
			set
			{
				if ((this._ngaythem != value))
				{
					this.OnngaythemChanging(value);
					this.SendPropertyChanging();
					this._ngaythem = value;
					this.SendPropertyChanged("ngaythem");
					this.OnngaythemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichcosanpham_giohang", Storage="_kichcosanpham", ThisKey="KichCoSanPham_id", OtherKey="id", IsForeignKey=true)]
		public kichcosanpham kichcosanpham
		{
			get
			{
				return this._kichcosanpham.Entity;
			}
			set
			{
				kichcosanpham previousValue = this._kichcosanpham.Entity;
				if (((previousValue != value) 
							|| (this._kichcosanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kichcosanpham.Entity = null;
						previousValue.giohangs.Remove(this);
					}
					this._kichcosanpham.Entity = value;
					if ((value != null))
					{
						value.giohangs.Add(this);
						this._KichCoSanPham_id = value.id;
					}
					else
					{
						this._KichCoSanPham_id = default(int);
					}
					this.SendPropertyChanged("kichcosanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_giohang", Storage="_khachhang", ThisKey="KhachHang_id", OtherKey="id", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.giohangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.giohangs.Add(this);
						this._KhachHang_id = value.id;
					}
					else
					{
						this._KhachHang_id = default(int);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kichcosanpham")]
	public partial class kichcosanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _kichco;
		
		private int _soluong;
		
		private System.Nullable<int> _SanPham_id;
		
		private System.Nullable<int> _LoaiSanPham_id;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntitySet<giohang> _giohangs;
		
		private EntityRef<loaisanpham> _loaisanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkichcoChanging(string value);
    partial void OnkichcoChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OnSanPham_idChanging(System.Nullable<int> value);
    partial void OnSanPham_idChanged();
    partial void OnLoaiSanPham_idChanging(System.Nullable<int> value);
    partial void OnLoaiSanPham_idChanged();
    #endregion
		
		public kichcosanpham()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._giohangs = new EntitySet<giohang>(new Action<giohang>(this.attach_giohangs), new Action<giohang>(this.detach_giohangs));
			this._loaisanpham = default(EntityRef<loaisanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kichco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kichco
		{
			get
			{
				return this._kichco;
			}
			set
			{
				if ((this._kichco != value))
				{
					this.OnkichcoChanging(value);
					this.SendPropertyChanging();
					this._kichco = value;
					this.SendPropertyChanged("kichco");
					this.OnkichcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPham_id", DbType="Int")]
		public System.Nullable<int> SanPham_id
		{
			get
			{
				return this._SanPham_id;
			}
			set
			{
				if ((this._SanPham_id != value))
				{
					this.OnSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._SanPham_id = value;
					this.SendPropertyChanged("SanPham_id");
					this.OnSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiSanPham_id", DbType="Int")]
		public System.Nullable<int> LoaiSanPham_id
		{
			get
			{
				return this._LoaiSanPham_id;
			}
			set
			{
				if ((this._LoaiSanPham_id != value))
				{
					if (this._loaisanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._LoaiSanPham_id = value;
					this.SendPropertyChanged("LoaiSanPham_id");
					this.OnLoaiSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichcosanpham_chitietdonhang", Storage="_chitietdonhangs", ThisKey="id", OtherKey="SanPham_id")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichcosanpham_giohang", Storage="_giohangs", ThisKey="id", OtherKey="KichCoSanPham_id")]
		public EntitySet<giohang> giohangs
		{
			get
			{
				return this._giohangs;
			}
			set
			{
				this._giohangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_kichcosanpham", Storage="_loaisanpham", ThisKey="LoaiSanPham_id", OtherKey="id", IsForeignKey=true)]
		public loaisanpham loaisanpham
		{
			get
			{
				return this._loaisanpham.Entity;
			}
			set
			{
				loaisanpham previousValue = this._loaisanpham.Entity;
				if (((previousValue != value) 
							|| (this._loaisanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaisanpham.Entity = null;
						previousValue.kichcosanphams.Remove(this);
					}
					this._loaisanpham.Entity = value;
					if ((value != null))
					{
						value.kichcosanphams.Add(this);
						this._LoaiSanPham_id = value.id;
					}
					else
					{
						this._LoaiSanPham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaisanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.kichcosanpham = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.kichcosanpham = null;
		}
		
		private void attach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.kichcosanpham = this;
		}
		
		private void detach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.kichcosanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _matkhau;
		
		private string _sdt;
		
		private string _ten;
		
		private string _forgotToken;
		
		private EntitySet<danhgiasanpham> _danhgiasanphams;
		
		private EntitySet<diachi> _diachis;
		
		private EntitySet<donhang> _donhangs;
		
		private EntitySet<giohang> _giohangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnforgotTokenChanging(string value);
    partial void OnforgotTokenChanged();
    #endregion
		
		public khachhang()
		{
			this._danhgiasanphams = new EntitySet<danhgiasanpham>(new Action<danhgiasanpham>(this.attach_danhgiasanphams), new Action<danhgiasanpham>(this.detach_danhgiasanphams));
			this._diachis = new EntitySet<diachi>(new Action<diachi>(this.attach_diachis), new Action<diachi>(this.detach_diachis));
			this._donhangs = new EntitySet<donhang>(new Action<donhang>(this.attach_donhangs), new Action<donhang>(this.detach_donhangs));
			this._giohangs = new EntitySet<giohang>(new Action<giohang>(this.attach_giohangs), new Action<giohang>(this.detach_giohangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(13)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forgotToken", DbType="VarChar(555)")]
		public string forgotToken
		{
			get
			{
				return this._forgotToken;
			}
			set
			{
				if ((this._forgotToken != value))
				{
					this.OnforgotTokenChanging(value);
					this.SendPropertyChanging();
					this._forgotToken = value;
					this.SendPropertyChanged("forgotToken");
					this.OnforgotTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_danhgiasanpham", Storage="_danhgiasanphams", ThisKey="id", OtherKey="KhachHang_id")]
		public EntitySet<danhgiasanpham> danhgiasanphams
		{
			get
			{
				return this._danhgiasanphams;
			}
			set
			{
				this._danhgiasanphams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_diachi", Storage="_diachis", ThisKey="id", OtherKey="KhachHang_id")]
		public EntitySet<diachi> diachis
		{
			get
			{
				return this._diachis;
			}
			set
			{
				this._diachis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_donhang", Storage="_donhangs", ThisKey="id", OtherKey="KhachHang_id")]
		public EntitySet<donhang> donhangs
		{
			get
			{
				return this._donhangs;
			}
			set
			{
				this._donhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_giohang", Storage="_giohangs", ThisKey="id", OtherKey="KhachHang_id")]
		public EntitySet<giohang> giohangs
		{
			get
			{
				return this._giohangs;
			}
			set
			{
				this._giohangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_danhgiasanphams(danhgiasanpham entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_danhgiasanphams(danhgiasanpham entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_diachis(diachi entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_diachis(diachi entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khuyenmai")]
	public partial class khuyenmai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private double _phantram;
		
		private System.DateTime _thoigian_bd;
		
		private System.Nullable<System.DateTime> _thoigian_kt;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnphantramChanging(double value);
    partial void OnphantramChanged();
    partial void Onthoigian_bdChanging(System.DateTime value);
    partial void Onthoigian_bdChanged();
    partial void Onthoigian_ktChanging(System.Nullable<System.DateTime> value);
    partial void Onthoigian_ktChanged();
    #endregion
		
		public khuyenmai()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(255)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phantram", DbType="Float NOT NULL")]
		public double phantram
		{
			get
			{
				return this._phantram;
			}
			set
			{
				if ((this._phantram != value))
				{
					this.OnphantramChanging(value);
					this.SendPropertyChanging();
					this._phantram = value;
					this.SendPropertyChanged("phantram");
					this.OnphantramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian_bd", DbType="DateTime NOT NULL")]
		public System.DateTime thoigian_bd
		{
			get
			{
				return this._thoigian_bd;
			}
			set
			{
				if ((this._thoigian_bd != value))
				{
					this.Onthoigian_bdChanging(value);
					this.SendPropertyChanging();
					this._thoigian_bd = value;
					this.SendPropertyChanged("thoigian_bd");
					this.Onthoigian_bdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian_kt", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoigian_kt
		{
			get
			{
				return this._thoigian_kt;
			}
			set
			{
				if ((this._thoigian_kt != value))
				{
					this.Onthoigian_ktChanging(value);
					this.SendPropertyChanging();
					this._thoigian_kt = value;
					this.SendPropertyChanged("thoigian_kt");
					this.Onthoigian_ktChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khuyenmai_sanpham", Storage="_sanphams", ThisKey="id", OtherKey="KhuyenMai_id")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.khuyenmai = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.khuyenmai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaisanpham")]
	public partial class loaisanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mausac;
		
		private string _hinhanh;
		
		private System.Nullable<int> _SanPham_id;
		
		private EntitySet<kichcosanpham> _kichcosanphams;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmausacChanging(string value);
    partial void OnmausacChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnSanPham_idChanging(System.Nullable<int> value);
    partial void OnSanPham_idChanged();
    #endregion
		
		public loaisanpham()
		{
			this._kichcosanphams = new EntitySet<kichcosanpham>(new Action<kichcosanpham>(this.attach_kichcosanphams), new Action<kichcosanpham>(this.detach_kichcosanphams));
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mausac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mausac
		{
			get
			{
				return this._mausac;
			}
			set
			{
				if ((this._mausac != value))
				{
					this.OnmausacChanging(value);
					this.SendPropertyChanging();
					this._mausac = value;
					this.SendPropertyChanged("mausac");
					this.OnmausacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SanPham_id", DbType="Int")]
		public System.Nullable<int> SanPham_id
		{
			get
			{
				return this._SanPham_id;
			}
			set
			{
				if ((this._SanPham_id != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSanPham_idChanging(value);
					this.SendPropertyChanging();
					this._SanPham_id = value;
					this.SendPropertyChanged("SanPham_id");
					this.OnSanPham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaisanpham_kichcosanpham", Storage="_kichcosanphams", ThisKey="id", OtherKey="LoaiSanPham_id")]
		public EntitySet<kichcosanpham> kichcosanphams
		{
			get
			{
				return this._kichcosanphams;
			}
			set
			{
				this._kichcosanphams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_loaisanpham", Storage="_sanpham", ThisKey="SanPham_id", OtherKey="id", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.loaisanphams.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.loaisanphams.Add(this);
						this._SanPham_id = value.id;
					}
					else
					{
						this._SanPham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kichcosanphams(kichcosanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = this;
		}
		
		private void detach_kichcosanphams(kichcosanpham entity)
		{
			this.SendPropertyChanging();
			entity.loaisanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NguoiDung")]
	public partial class QL_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _HoatDong;
		
		private EntitySet<QL_NguoiDungNhomNguoiDung> _QL_NguoiDungNhomNguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoatDongChanging(System.Nullable<bool> value);
    partial void OnHoatDongChanged();
    #endregion
		
		public QL_NguoiDung()
		{
			this._QL_NguoiDungNhomNguoiDungs = new EntitySet<QL_NguoiDungNhomNguoiDung>(new Action<QL_NguoiDungNhomNguoiDung>(this.attach_QL_NguoiDungNhomNguoiDungs), new Action<QL_NguoiDungNhomNguoiDung>(this.detach_QL_NguoiDungNhomNguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(100)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="Bit")]
		public System.Nullable<bool> HoatDong
		{
			get
			{
				return this._HoatDong;
			}
			set
			{
				if ((this._HoatDong != value))
				{
					this.OnHoatDongChanging(value);
					this.SendPropertyChanging();
					this._HoatDong = value;
					this.SendPropertyChanged("HoatDong");
					this.OnHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_NguoiDungNhomNguoiDung", Storage="_QL_NguoiDungNhomNguoiDungs", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<QL_NguoiDungNhomNguoiDung> QL_NguoiDungNhomNguoiDungs
		{
			get
			{
				return this._QL_NguoiDungNhomNguoiDungs;
			}
			set
			{
				this._QL_NguoiDungNhomNguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_NguoiDungNhomNguoiDungs(QL_NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = this;
		}
		
		private void detach_QL_NguoiDungNhomNguoiDungs(QL_NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NguoiDungNhomNguoiDung")]
	public partial class QL_NguoiDungNhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MaNhomNguoiDung;
		
		private string _GhiChu;
		
		private EntityRef<QL_NguoiDung> _QL_NguoiDung;
		
		private EntityRef<QL_NhomNguoiDung> _QL_NhomNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_NguoiDungNhomNguoiDung()
		{
			this._QL_NguoiDung = default(EntityRef<QL_NguoiDung>);
			this._QL_NhomNguoiDung = default(EntityRef<QL_NhomNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._QL_NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					if (this._QL_NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_NguoiDungNhomNguoiDung", Storage="_QL_NguoiDung", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public QL_NguoiDung QL_NguoiDung
		{
			get
			{
				return this._QL_NguoiDung.Entity;
			}
			set
			{
				QL_NguoiDung previousValue = this._QL_NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NguoiDung.Entity = null;
						previousValue.QL_NguoiDungNhomNguoiDungs.Remove(this);
					}
					this._QL_NguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_NguoiDungNhomNguoiDungs.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("QL_NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomNguoiDung_QL_NguoiDungNhomNguoiDung", Storage="_QL_NhomNguoiDung", ThisKey="MaNhomNguoiDung", OtherKey="MaNhom", IsForeignKey=true)]
		public QL_NhomNguoiDung QL_NhomNguoiDung
		{
			get
			{
				return this._QL_NhomNguoiDung.Entity;
			}
			set
			{
				QL_NhomNguoiDung previousValue = this._QL_NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhomNguoiDung.Entity = null;
						previousValue.QL_NguoiDungNhomNguoiDungs.Remove(this);
					}
					this._QL_NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_NguoiDungNhomNguoiDungs.Add(this);
						this._MaNhomNguoiDung = value.MaNhom;
					}
					else
					{
						this._MaNhomNguoiDung = default(string);
					}
					this.SendPropertyChanged("QL_NhomNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhomNguoiDung")]
	public partial class QL_NhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private string _GhiChu;
		
		private EntitySet<QL_NguoiDungNhomNguoiDung> _QL_NguoiDungNhomNguoiDungs;
		
		private EntitySet<QL_PhanQuyen> _QL_PhanQuyens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_NhomNguoiDung()
		{
			this._QL_NguoiDungNhomNguoiDungs = new EntitySet<QL_NguoiDungNhomNguoiDung>(new Action<QL_NguoiDungNhomNguoiDung>(this.attach_QL_NguoiDungNhomNguoiDungs), new Action<QL_NguoiDungNhomNguoiDung>(this.detach_QL_NguoiDungNhomNguoiDungs));
			this._QL_PhanQuyens = new EntitySet<QL_PhanQuyen>(new Action<QL_PhanQuyen>(this.attach_QL_PhanQuyens), new Action<QL_PhanQuyen>(this.detach_QL_PhanQuyens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomNguoiDung_QL_NguoiDungNhomNguoiDung", Storage="_QL_NguoiDungNhomNguoiDungs", ThisKey="MaNhom", OtherKey="MaNhomNguoiDung")]
		public EntitySet<QL_NguoiDungNhomNguoiDung> QL_NguoiDungNhomNguoiDungs
		{
			get
			{
				return this._QL_NguoiDungNhomNguoiDungs;
			}
			set
			{
				this._QL_NguoiDungNhomNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomNguoiDung_QL_PhanQuyen", Storage="_QL_PhanQuyens", ThisKey="MaNhom", OtherKey="MaNhomNguoiDung")]
		public EntitySet<QL_PhanQuyen> QL_PhanQuyens
		{
			get
			{
				return this._QL_PhanQuyens;
			}
			set
			{
				this._QL_PhanQuyens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_NguoiDungNhomNguoiDungs(QL_NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomNguoiDung = this;
		}
		
		private void detach_QL_NguoiDungNhomNguoiDungs(QL_NguoiDungNhomNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomNguoiDung = null;
		}
		
		private void attach_QL_PhanQuyens(QL_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomNguoiDung = this;
		}
		
		private void detach_QL_PhanQuyens(QL_PhanQuyen entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_PhanQuyen")]
	public partial class QL_PhanQuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomNguoiDung;
		
		private string _MaManHinh;
		
		private bool _CoQuyen;
		
		private EntityRef<DM_ManHinh> _DM_ManHinh;
		
		private EntityRef<QL_NhomNguoiDung> _QL_NhomNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnCoQuyenChanging(bool value);
    partial void OnCoQuyenChanged();
    #endregion
		
		public QL_PhanQuyen()
		{
			this._DM_ManHinh = default(EntityRef<DM_ManHinh>);
			this._QL_NhomNguoiDung = default(EntityRef<QL_NhomNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					if (this._QL_NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._DM_ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuyen", DbType="Bit NOT NULL")]
		public bool CoQuyen
		{
			get
			{
				return this._CoQuyen;
			}
			set
			{
				if ((this._CoQuyen != value))
				{
					this.OnCoQuyenChanging(value);
					this.SendPropertyChanging();
					this._CoQuyen = value;
					this.SendPropertyChanged("CoQuyen");
					this.OnCoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_ManHinh_QL_PhanQuyen", Storage="_DM_ManHinh", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public DM_ManHinh DM_ManHinh
		{
			get
			{
				return this._DM_ManHinh.Entity;
			}
			set
			{
				DM_ManHinh previousValue = this._DM_ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._DM_ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_ManHinh.Entity = null;
						previousValue.QL_PhanQuyens.Remove(this);
					}
					this._DM_ManHinh.Entity = value;
					if ((value != null))
					{
						value.QL_PhanQuyens.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(string);
					}
					this.SendPropertyChanged("DM_ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomNguoiDung_QL_PhanQuyen", Storage="_QL_NhomNguoiDung", ThisKey="MaNhomNguoiDung", OtherKey="MaNhom", IsForeignKey=true)]
		public QL_NhomNguoiDung QL_NhomNguoiDung
		{
			get
			{
				return this._QL_NhomNguoiDung.Entity;
			}
			set
			{
				QL_NhomNguoiDung previousValue = this._QL_NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhomNguoiDung.Entity = null;
						previousValue.QL_PhanQuyens.Remove(this);
					}
					this._QL_NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_PhanQuyens.Add(this);
						this._MaNhomNguoiDung = value.MaNhom;
					}
					else
					{
						this._MaNhomNguoiDung = default(string);
					}
					this.SendPropertyChanged("QL_NhomNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private string _mota;
		
		private double _gia;
		
		private string _gioitinh;
		
		private System.DateTime _ngaytao;
		
		private int _DanhMuc_id;
		
		private System.Nullable<int> _KhuyenMai_id;
		
		private string _anhdaidien;
		
		private EntitySet<loaisanpham> _loaisanphams;
		
		private EntityRef<khuyenmai> _khuyenmai;
		
		private EntityRef<danhmuc> _danhmuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OngiaChanging(double value);
    partial void OngiaChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaytaoChanging(System.DateTime value);
    partial void OnngaytaoChanged();
    partial void OnDanhMuc_idChanging(int value);
    partial void OnDanhMuc_idChanged();
    partial void OnKhuyenMai_idChanging(System.Nullable<int> value);
    partial void OnKhuyenMai_idChanged();
    partial void OnanhdaidienChanging(string value);
    partial void OnanhdaidienChanged();
    #endregion
		
		public sanpham()
		{
			this._loaisanphams = new EntitySet<loaisanpham>(new Action<loaisanpham>(this.attach_loaisanphams), new Action<loaisanpham>(this.detach_loaisanphams));
			this._khuyenmai = default(EntityRef<khuyenmai>);
			this._danhmuc = default(EntityRef<danhmuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(1000)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float NOT NULL")]
		public double gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime NOT NULL")]
		public System.DateTime ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhMuc_id", DbType="Int NOT NULL")]
		public int DanhMuc_id
		{
			get
			{
				return this._DanhMuc_id;
			}
			set
			{
				if ((this._DanhMuc_id != value))
				{
					if (this._danhmuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDanhMuc_idChanging(value);
					this.SendPropertyChanging();
					this._DanhMuc_id = value;
					this.SendPropertyChanged("DanhMuc_id");
					this.OnDanhMuc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai_id", DbType="Int")]
		public System.Nullable<int> KhuyenMai_id
		{
			get
			{
				return this._KhuyenMai_id;
			}
			set
			{
				if ((this._KhuyenMai_id != value))
				{
					if (this._khuyenmai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKhuyenMai_idChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai_id = value;
					this.SendPropertyChanged("KhuyenMai_id");
					this.OnKhuyenMai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anhdaidien", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string anhdaidien
		{
			get
			{
				return this._anhdaidien;
			}
			set
			{
				if ((this._anhdaidien != value))
				{
					this.OnanhdaidienChanging(value);
					this.SendPropertyChanging();
					this._anhdaidien = value;
					this.SendPropertyChanged("anhdaidien");
					this.OnanhdaidienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_loaisanpham", Storage="_loaisanphams", ThisKey="id", OtherKey="SanPham_id")]
		public EntitySet<loaisanpham> loaisanphams
		{
			get
			{
				return this._loaisanphams;
			}
			set
			{
				this._loaisanphams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khuyenmai_sanpham", Storage="_khuyenmai", ThisKey="KhuyenMai_id", OtherKey="id", IsForeignKey=true)]
		public khuyenmai khuyenmai
		{
			get
			{
				return this._khuyenmai.Entity;
			}
			set
			{
				khuyenmai previousValue = this._khuyenmai.Entity;
				if (((previousValue != value) 
							|| (this._khuyenmai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khuyenmai.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._khuyenmai.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._KhuyenMai_id = value.id;
					}
					else
					{
						this._KhuyenMai_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("khuyenmai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_danhmuc", ThisKey="DanhMuc_id", OtherKey="id", IsForeignKey=true)]
		public danhmuc danhmuc
		{
			get
			{
				return this._danhmuc.Entity;
			}
			set
			{
				danhmuc previousValue = this._danhmuc.Entity;
				if (((previousValue != value) 
							|| (this._danhmuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._danhmuc.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._danhmuc.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._DanhMuc_id = value.id;
					}
					else
					{
						this._DanhMuc_id = default(int);
					}
					this.SendPropertyChanged("danhmuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_loaisanphams(loaisanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_loaisanphams(loaisanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
}
#pragma warning restore 1591
